version: '2'  
services:  
    mariadb-5.2.3: # OK
        build: ./mariadb-5.2.3
        image: ansible_mysql_user/mariadb:5.2.3
        ports: [ "3307:3306" ]
    mariadb-5.2.11: # OK
        build: ./mariadb-5.2.11
        image: ansible_mysql_user/mariadb:5.2.11
        ports: [ "3308:3306" ]
    mariadb-5.2.14: # OK
        build: ./mariadb-5.2.14
        image: ansible_mysql_user/mariadb:5.2.14
        ports: [ "3309:3306" ]
    mariadb-5.3.5: # OK
        build: ./mariadb-5.3.5
        image: ansible_mysql_user/mariadb:5.3.5
        ports: [ "3310:3306" ]
    mariadb-5.3.12: # OK
        build: ./mariadb-5.3.12
        image: ansible_mysql_user/mariadb:5.3.12
        ports: [ "3311:3306" ]
    mariadb-5.5.23: # OK
        build: ./mariadb-5.5.23
        image: ansible_mysql_user/mariadb:5.5.23
        ports: [ "3312:3306" ]
    mariadb-5.5.50: # OK
        build: ./mariadb-5.5.50
        image: ansible_mysql_user/mariadb:5.5.50
        ports: [ "3313:3306" ]

    mysql-5.0.96: # OK
        build: ./mysql-5.0.96
        image: ansible_mysql_user/mysql:5.0.96
        ports: [ "3314:3306" ]
    mysql-5.1.72: # OK
        build: ./mysql-5.1.72
        image: ansible_mysql_user/mysql:5.1.72
        ports: [ "3315:3306" ]
    mysql-5.5.8: # OK
        build: ./mysql-5.5.8
        image: ansible_mysql_user/mysql:5.5.8
        ports: [ "3316:3306" ]
    mysql-5.5.50: # OK
        build: ./mysql-5.5.50
        image: ansible_mysql_user/mysql:5.5.50
        ports: [ "3317:3306" ]
    mysql-5.6.31: # OK
        build: ./mysql-5.6.31
        image: ansible_mysql_user/mysql:5.6.31
        ports: [ "3318:3306" ]
    mysql-5.7.13: # 
        build: ./mysql-5.7.13
        image: ansible_mysql_user/mysql:5.7.13
        ports: [ "3319:3306" ]

    ansible:
        build: ./ansible
        image: ansible_mysql_user/ansible
        ports: [ "2210:22" ]
        links:
            - mariadb-5.2.3
            - mariadb-5.2.11
            - mariadb-5.2.14
            - mariadb-5.3.5
            - mariadb-5.3.12
            - mariadb-5.5.23
            - mariadb-5.5.50
            - mysql-5.0.96
            - mysql-5.1.72
            - mysql-5.5.8
            - mysql-5.5.50
            - mysql-5.6.31
            - mysql-5.7.13
